# Generated by Django 5.1.4 on 2025-02-12 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_taskdetails_assign_to_alter_task_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetails',
            name='task',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='details', to='tasks.task'),
        ),
    ]
