# Generated by Django 5.1.4 on 2025-02-23 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_taskdetails_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='employee',
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.project'),
        ),
        migrations.AlterField(
            model_name='taskdetails',
            name='task',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='details', to='tasks.task'),
        ),
    ]
