# Generated by Django 5.1.4 on 2025-02-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdetails',
            name='asset',
            field=models.ImageField(blank=True, null=True, upload_to='task_asset'),
        ),
    ]
