# Generated by Django 5.1.4 on 2025-02-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_taskdetails_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetails',
            name='asset',
            field=models.ImageField(blank=True, default='task_asset/download.png', null=True, upload_to='task_asset'),
        ),
    ]
